# Generated by Django 2.2.4 on 2023-12-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_job_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='addres',
            field=models.CharField(default='company', max_length=45),
        ),
    ]
