# Generated by Django 2.2.4 on 2023-12-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_company_addres'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='due_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
