# Generated by Django 2.2.4 on 2023-12-22 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_job_due_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rate',
        ),
    ]
